from django.core.management.base import BaseCommand
from core.models import TourPackage, Destination, Place
from django.utils.text import slugify

DESTINATIONS_DATA = [
    {"name": "Jaipur", "state": "rajasthan", "description": "The Pink City, capital of Rajasthan, known for stunning forts and palaces.", "is_featured": True},
    {"name": "Goa", "state": "goa", "description": "India's beach paradise with golden sands, Portuguese heritage, and vibrant nightlife.", "is_featured": True},
    {"name": "Munnar", "state": "kerala", "description": "Misty hill station in Kerala surrounded by tea plantations and waterfalls.", "is_featured": True},
    {"name": "Manali", "state": "himachal_pradesh", "description": "Adventure capital of India, nestled in the Himalayas with snow-capped peaks.", "is_featured": True},
    {"name": "Srinagar", "state": "kashmir", "description": "The summer capital of J&K, famous for its Dal Lake and houseboats.", "is_featured": True},
    {"name": "Rishikesh", "state": "uttarakhand", "description": "Yoga capital of the world and adventure hub on the banks of the Ganges.", "is_featured": True},
    {"name": "Agra", "state": "uttar_pradesh", "description": "Home of the iconic Taj Mahal, one of the Seven Wonders of the World.", "is_featured": True},
    {"name": "Andaman Islands", "state": "andaman", "description": "Crystal-clear waters, coral reefs, and pristine beaches in the Bay of Bengal.", "is_featured": True},
]

PACKAGES_DATA = [
    {
        "title": "Rajasthan Royal Heritage Tour",
        "state": "rajasthan",
        "city_name": "Jaipur",
        "description": "Experience the grandeur of Rajasthan! Explore the majestic forts and palaces of Jaipur, Jodhpur, and Udaipur. Ride camels in the Thar Desert, witness the spectacular Mehrangarh Fort, and cruise on Pichola Lake.",
        "highlights": "Amber Fort & City Palace Jaipur\nMehrangarh Fort Jodhpur\nUdaipur City of Lakes\nDesert Camp Jaisalmer\nCamel Safari at Sam Dunes",
        "duration_days": 8,
        "max_group_size": 20,
        "price_per_person": 28500,
        "discount_percent": 10,
        "difficulty": "easy",
        "best_season": "winter",
        "transportation": "private_cab",
        "accommodation": "hotel",
        "is_featured": True,
    },
    {
        "title": "Goa Beach Paradise Escape",
        "state": "goa",
        "city_name": "Goa",
        "description": "Sun, sand, and sea! The ultimate Goa beach getaway. Relax on pristine beaches, explore Portuguese colonial architecture, and experience the legendary Goan nightlife.",
        "highlights": "Baga & Calangute Beaches\nDudhsagar Falls Visit\nOld Goa Churches (UNESCO)\nSpice Plantation Tour\nSunset Cruise",
        "duration_days": 7,
        "max_group_size": 25,
        "price_per_person": 18500,
        "discount_percent": 15,
        "difficulty": "easy",
        "best_season": "winter",
        "transportation": "private_cab",
        "accommodation": "resort",
        "is_featured": True,
    },
    {
        "title": "Kerala God's Own Country Tour",
        "state": "kerala",
        "city_name": "Munnar",
        "description": "Discover Kerala's breathtaking beauty — misty tea gardens of Munnar, tranquil backwaters of Alleppey, and wildlife at Periyar.",
        "highlights": "Munnar Tea Gardens\nAlleppey Backwater Houseboat Stay\nPeriyar Wildlife Sanctuary\nKovalam Beach\nAyurvedic Spa",
        "duration_days": 9,
        "max_group_size": 18,
        "price_per_person": 32000,
        "discount_percent": 8,
        "difficulty": "easy",
        "best_season": "winter",
        "transportation": "private_cab",
        "accommodation": "houseboat",
        "is_featured": True,
    },
    {
        "title": "Manali Adventure & Snow Expedition",
        "state": "himachal_pradesh",
        "city_name": "Manali",
        "description": "The ultimate Himalayan adventure! Rohtang Pass in snow, paragliding at Solang Valley, and river rafting on the Beas.",
        "highlights": "Rohtang Pass (Snow Point)\nSolang Valley Paragliding\nBeas River Rafting\nHadimba Devi Temple\nOld Manali",
        "duration_days": 7,
        "max_group_size": 15,
        "price_per_person": 22000,
        "discount_percent": 12,
        "difficulty": "moderate",
        "best_season": "summer",
        "transportation": "jeep",
        "accommodation": "hotel",
        "is_featured": True,
    },
    {
        "title": "Kashmir Heaven on Earth",
        "state": "kashmir",
        "city_name": "Srinagar",
        "description": "Experience the unparalleled beauty of Kashmir! Stay on a traditional houseboat on Dal Lake and witness the magical Mughal Gardens.",
        "highlights": "Dal Lake Shikara Ride\nGulmarg Gondola Ride\nPahalgam Betaab Valley\nMughal Gardens\nSonamarg Glacier Visit",
        "duration_days": 7,
        "max_group_size": 16,
        "price_per_person": 26000,
        "discount_percent": 5,
        "difficulty": "easy",
        "best_season": "summer",
        "transportation": "private_cab",
        "accommodation": "houseboat",
        "is_featured": True,
    },
    # --- EXTRA PACKAGES MERGED ---
    {
        "title": "Sikkim & Darjeeling — The Himalayan Jewel",
        "state": "west_bengal",
        "city_name": "Gangtok",
        "description": "Explore the mystical land of Sikkim and Darjeeling. Witness the sunrise at Tiger Hill and visit Tsomgo Lake.",
        "highlights": "Tiger Hill Sunrise\nTsomgo Lake & Baba Mandir\nRumtek Monastery\nTea Garden Visit\nToy Train Ride",
        "duration_days": 7,
        "max_group_size": 15,
        "price_per_person": 24500,
        "discount_percent": 10,
        "difficulty": "moderate",
        "best_season": "summer",
        "transportation": "private_cab",
        "accommodation": "hotel",
        "is_featured": True,
    },
    {
        "title": "Meghalaya — The Abode of Clouds",
        "state": "northeast",
        "city_name": "Shillong",
        "description": "A journey to the wettest place on Earth! Explore the living root bridges and crystal clear Umngot river.",
        "highlights": "Double Decker Living Root Bridge\nDawki Boat Ride\nCherrapunji Falls\nElephant Falls\nShillong Peak",
        "duration_days": 6,
        "max_group_size": 12,
        "price_per_person": 21000,
        "discount_percent": 5,
        "difficulty": "challenging",
        "best_season": "monsoon",
        "transportation": "jeep",
        "accommodation": "homestay",
        "is_featured": True,
    },
    {
        "title": "Varanasi & Sarnath — Spiritual Awakening",
        "state": "uttar_pradesh",
        "city_name": "Varanasi",
        "description": "Experience the spiritual heart of India. Witness the grand Ganga Aarti and explore the ancient ruins of Sarnath.",
        "highlights": "Evening Ganga Aarti\nSunrise Boat Ride on Ganges\nKashi Vishwanath Temple\nSarnath Buddhist Site\nBanarasi Saree Center",
        "duration_days": 4,
        "max_group_size": 30,
        "price_per_person": 12500,
        "discount_percent": 0,
        "difficulty": "easy",
        "best_season": "winter",
        "transportation": "private_cab",
        "accommodation": "hotel",
        "is_featured": False,
    },
    {
        "title": "Rann of Kutch — The White Desert Magic",
        "state": "gujarat",
        "city_name": "Bhuj",
        "description": "Experience the Rann Utsav! Witness the endless white salt desert under the moonlight.",
        "highlights": "White Rann under Full Moon\nRann Utsav Cultural Nights\nTraditional Bhunga Stay\nKala Dungar\nHandicraft Village",
        "duration_days": 4,
        "max_group_size": 20,
        "price_per_person": 16500,
        "discount_percent": 5,
        "difficulty": "easy",
        "best_season": "winter",
        "transportation": "bus",
        "accommodation": "camp",
        "is_featured": True,
    },
    {
        "title": "Hampi & Badami — The Forgotten Empire",
        "state": "karnataka",
        "city_name": "Hampi",
        "description": "Explore the boulder-strewn landscape, magnificent ruins, and rock-cut temples of Badami.",
        "highlights": "Virupaksha Temple\nVitthala Temple\nBadami Cave Temples\nPattadakal UNESCO Site\nCoracle Ride",
        "duration_days": 5,
        "max_group_size": 15,
        "price_per_person": 18500,
        "discount_percent": 10,
        "difficulty": "moderate",
        "best_season": "winter",
        "transportation": "private_cab",
        "accommodation": "hotel",
        "is_featured": False,
    },
    {
        "title": "Ladakh — The Land of High Passes",
        "state": "kashmir",
        "city_name": "Leh",
        "description": "A high-altitude adventure like no other. Crystal clear lakes and ancient monasteries.",
        "highlights": "Pangong Tso Lake\nKhardung La Pass\nNubra Valley Camel Safari\nShanti Stupa\nMagnetic Hill",
        "duration_days": 9,
        "max_group_size": 10,
        "price_per_person": 38000,
        "discount_percent": 0,
        "difficulty": "extreme",
        "best_season": "summer",
        "transportation": "jeep",
        "accommodation": "camp",
        "is_featured": True,
    },
    {
        "title": "Khajuraho & Orchha — Art & Heritage",
        "state": "madhya_pradesh",
        "city_name": "Khajuraho",
        "description": "Marvel at the intricate erotic sculptures of Khajuraho and the medieval charm of Orchha.",
        "highlights": "Western Group of Temples\nLight & Sound Show\nOrchha Fort Complex\nCenotaphs on Betwa River\nPanna National Park Safari",
        "duration_days": 5,
        "max_group_size": 20,
        "price_per_person": 15500,
        "discount_percent": 15,
        "difficulty": "easy",
        "best_season": "winter",
        "transportation": "private_cab",
        "accommodation": "hotel",
        "is_featured": False,
    },
    {
        "title": "Andaman Scuba Adventure",
        "state": "andaman",
        "city_name": "Havelock",
        "description": "Dive into the blue! The best scuba diving experience in India with rich coral reefs.",
        "highlights": "PADI Discovery Scuba Dive\nRadhanagar Beach\nElephant Beach Trek\nNight Kayaking\nSeafood Barbecue",
        "duration_days": 5,
        "max_group_size": 12,
        "price_per_person": 29500,
        "discount_percent": 8,
        "difficulty": "moderate",
        "best_season": "winter",
        "transportation": "private_cab",
        "accommodation": "resort",
        "is_featured": False,
    },
    {
        "title": "Ooty & Kodaikanal — Southern Hill Stations",
        "state": "tamil_nadu",
        "city_name": "Ooty",
        "description": "Escape to the Nilgiris. Enjoy the cool breeze and tea gardens of South India.",
        "highlights": "Nilgiri Mountain Railway\nBotanical Gardens Ooty\nKodaikanal Lake Boating\nCoaker's Walk\nDolphin's Nose",
        "duration_days": 6,
        "max_group_size": 25,
        "price_per_person": 19000,
        "discount_percent": 10,
        "difficulty": "easy",
        "best_season": "summer",
        "transportation": "bus",
        "accommodation": "hotel",
        "is_featured": False,
    },
    {
        "title": "Golden Temple & Amritsar Heritage",
        "state": "punjab",
        "city_name": "Amritsar",
        "description": "Experience the divinity of the Golden Temple and the patriotic fervor at the Wagah Border.",
        "highlights": "Golden Temple\nWagah Border Ceremony\nJallianwala Bagh\nPartition Museum\nStreet Food Walk",
        "duration_days": 3,
        "max_group_size": 40,
        "price_per_person": 8500,
        "discount_percent": 5,
        "difficulty": "easy",
        "best_season": "winter",
        "transportation": "private_cab",
        "accommodation": "hotel",
        "is_featured": False,
    },
    {
        "title": "Spiti Valley — The Middle Land",
        "state": "himachal_pradesh",
        "city_name": "Kaza",
        "description": "A rugged Himalayan journey through the cold desert and ancient monasteries.",
        "highlights": "Key Monastery\nChandratal Lake Camping\nWorld's Highest Post Office\nPin Valley National Park\nKunzum Pass",
        "duration_days": 10,
        "max_group_size": 8,
        "price_per_person": 32500,
        "discount_percent": 0,
        "difficulty": "extreme",
        "best_season": "summer",
        "transportation": "jeep",
        "accommodation": "homestay",
        "is_featured": False,
    },
    {
        "title": "Pondicherry — Little France in India",
        "state": "tamil_nadu",
        "city_name": "Pondicherry",
        "description": "Explore the charming French Quarter, relax on serene beaches, and find peace at Auroville.",
        "highlights": "French Quarter Walk\nAuroville & Matrimandir\nParadise Beach\nPromenade Beach\nFrench Bakery",
        "duration_days": 4,
        "max_group_size": 20,
        "price_per_person": 11500,
        "discount_percent": 12,
        "difficulty": "easy",
        "best_season": "winter",
        "transportation": "private_cab",
        "accommodation": "hotel",
        "is_featured": False,
    },
    {
        "title": "Sundarbans — The Mangrove Kingdom",
        "state": "west_bengal",
        "city_name": "Sundarbans",
        "description": "Explore the largest mangrove forest in the world and spot the Royal Bengal Tiger.",
        "highlights": "Jungle Boat Safari\nTiger Spotting Watchtowers\nCrocodile Center\nLocal Folk Performance\nMangrove Boardwalk",
        "duration_days": 3,
        "max_group_size": 15,
        "price_per_person": 9500,
        "discount_percent": 5,
        "difficulty": "moderate",
        "best_season": "winter",
        "transportation": "bus",
        "accommodation": "resort",
        "is_featured": False,
    },
    {
        "title": "Konark & Puri — Eastern Spiritual Tour",
        "state": "west_bengal",
        "city_name": "Puri",
        "description": "Visit the world-famous Sun Temple at Konark and the sacred Jagannath Temple at Puri.",
        "highlights": "Konark Sun Temple\nJagannath Puri Temple\nChilika Lake\nPuri Beach Market\nRaghurajpur Village",
        "duration_days": 5,
        "max_group_size": 30,
        "price_per_person": 14000,
        "discount_percent": 10,
        "difficulty": "easy",
        "best_season": "winter",
        "transportation": "private_cab",
        "accommodation": "hotel",
        "is_featured": False,
    },
    {
        "title": "Jim Corbett — Tiger Territory Safari",
        "state": "uttarakhand",
        "city_name": "Ramnagar",
        "description": "A thrilling wildlife experience in India's oldest national park.",
        "highlights": "Jeep Safari\nForest Lodge Stay\nGarjiya Devi Temple\nElephant Safari\nBird Watching",
        "itinerary": "Arrive Ramnagar, check-in to Dhikala Forest Lodge\nMorning jeep safari in Bijrani Range\nElephant back safari at dawn into core zone\nGarjiya Devi Temple visit & evening bird watching\nDepart Ramnagar",
        "duration_days": 4,
        "max_group_size": 12,
        "price_per_person": 15000,
        "discount_percent": 5,
        "difficulty": "moderate",
        "best_season": "all",
        "transportation": "jeep",
        "accommodation": "resort",
        "hotel_name": "Dhikala Forest Lodge",
        "hotel_star_rating": 4,
        "transport_details": "Private Mahindra Thar 4x4 Jeep Safari",
        "is_featured": True,
    },
    # ── WILDLIFE PACKAGES ──────────────────────────────────────
    {
        "title": "Kaziranga — One-Horned Rhino Safari",
        "state": "northeast",
        "city_name": "Kaziranga",
        "description": "Home to two-thirds of the world's one-horned rhinoceros population, Kaziranga is a UNESCO World Heritage Site on the Brahmaputra floodplains. Spot tigers, wild elephants and migratory birds.",
        "highlights": "Jeep Safari in Kohora Range\nElephant Safari at Dawn\nBagori Range Exploration\nBrahmaputra River Cruise\nBird Watching (500+ species)",
        "itinerary": "Arrive Guwahati, drive 4hrs to Kaziranga — check-in Iora Resort\nMorning elephant safari into Central Range at sunrise\nJeep safari in Kohora Range — spot rhinos & elephants\nBird watching tour & Bagori Range jeep safari\nBrahmaputra river cruise at sunset, depart Guwahati",
        "duration_days": 5,
        "max_group_size": 10,
        "price_per_person": 18500,
        "discount_percent": 8,
        "difficulty": "easy",
        "best_season": "winter",
        "transportation": "jeep",
        "accommodation": "resort",
        "hotel_name": "Iora Resort Kaziranga",
        "hotel_star_rating": 4,
        "transport_details": "AC Innova from Guwahati + Forest Jeep Safari",
        "is_featured": True,
    },
    {
        "title": "Ranthambore — The Tiger's Domain",
        "state": "rajasthan",
        "city_name": "Sawai Madhopur",
        "description": "India's most celebrated tiger reserve. Ranthambore's dramatic landscape of crumbling forts and emerald lakes forms the perfect backdrop for spotting the Royal Bengal Tiger in the wild.",
        "highlights": "Tiger Safari Zones 1-5\nRanthambore Fort (UNESCO)\nPadam Talao Lake\nNighttime Leopard Trail\nNaturalist Guided Walk",
        "itinerary": "Arrive Sawai Madhopur — check-in Khem Villas eco-resort\nMorning Canter safari in Zone 1 & 2 — tiger sighting attempt\nAfternoon jeep safari in Zone 3 & 4 with naturalist guide\nVisit Ranthambore Fort & Padam Talao at golden hour\nEarly morning Zone 5 exclusive jeep safari — depart",
        "duration_days": 5,
        "max_group_size": 8,
        "price_per_person": 27500,
        "discount_percent": 0,
        "difficulty": "easy",
        "best_season": "winter",
        "transportation": "jeep",
        "accommodation": "resort",
        "hotel_name": "Khem Villas Eco Resort",
        "hotel_star_rating": 5,
        "transport_details": "Private Gypsy Jeep (6-seater) for all safaris",
        "is_featured": True,
    },
    {
        "title": "Periyar Wildlife Reserve — Jungle Immersion",
        "state": "kerala",
        "city_name": "Thekkady",
        "description": "A biodiversity hotspot in the Western Ghats, Periyar is home to wild elephants, tigers and over 260 bird species. Float on its lake, bamboo-raft its rivers and walk its forest trails.",
        "highlights": "Periyar Lake Boat Cruise\nBamboo Rafting on Periyar River\nSpice Plantation Walk\nElephant Observation Point\nBorder Hiking Trail",
        "itinerary": "Arrive Thekkady — check-in Spice Village Resort\nPeriyar Lake boat cruise — spot wild elephants & bison\nBamboo rafting expedition on Periyar River with ranger\nSpice plantation tour — cardamom, pepper & vanilla\nBorder hiking trail with naturalist — depart Kochi",
        "duration_days": 5,
        "max_group_size": 12,
        "price_per_person": 22000,
        "discount_percent": 5,
        "difficulty": "moderate",
        "best_season": "winter",
        "transportation": "private_cab",
        "accommodation": "resort",
        "hotel_name": "Spice Village CGH Earth Resort",
        "hotel_star_rating": 4,
        "transport_details": "AC Toyota Etios from Kochi + bamboo raft",
        "is_featured": False,
    },
    # ── CULTURAL PACKAGES ──────────────────────────────────────
    {
        "title": "Mysore Royal Heritage — Palace & Culture",
        "state": "karnataka",
        "city_name": "Mysore",
        "description": "The city of palaces! Mysore dazzles with its silk, sandalwood and the grand Mysore Palace — India's second most visited monument after the Taj Mahal.",
        "highlights": "Mysore Palace Illumination\nChamundeswari Temple\nDevaraja Market Bazaar\nBrindavan Gardens\nSilk Weaving Factory",
        "itinerary": "Arrive Mysore — check-in Radisson Blu\nMysore Palace tour & Devaraja Market silk shopping\nChamundi Hills & Chamundeswari Temple at sunrise\nBrindavan Gardens musical fountain evening show\nSilk weaving factory & Mysore Zoo — depart Bengaluru",
        "duration_days": 5,
        "max_group_size": 25,
        "price_per_person": 14500,
        "discount_percent": 10,
        "difficulty": "easy",
        "best_season": "winter",
        "transportation": "private_cab",
        "accommodation": "hotel",
        "hotel_name": "Radisson Blu Plaza Hotel Mysore",
        "hotel_star_rating": 4,
        "transport_details": "Private Toyota Innova from Bengaluru + city cab",
        "is_featured": False,
    },
    {
        "title": "Pushkar & Ajmer — Sacred Rajasthan",
        "state": "rajasthan",
        "city_name": "Pushkar",
        "description": "Home to the only Brahma Temple in the world, Pushkar is a mystical desert town wrapped around a sacred lake. Combine with the spiritual Dargah Sharif in Ajmer for a soulful experience.",
        "highlights": "Brahma Temple Pushkar\nPushkar Lake Ghats\nPushkar Camel Fair Grounds\nAjmer Dargah Sharif\nAdhai Din Ka Jhopra Ruins",
        "itinerary": "Arrive Jaipur — drive 3hrs to Pushkar, check-in Hotel Brahma Horizon\nPushkar Lake ghats morning aarti & Brahma Temple darshan\nCamel fair grounds, local bazaar & rose garden visit\nAjmer Dargah Sharif & Adhai Din Ka Jhopra ruins\nReturn to Jaipur for onward travel — depart",
        "duration_days": 4,
        "max_group_size": 30,
        "price_per_person": 9500,
        "discount_percent": 5,
        "difficulty": "easy",
        "best_season": "all",
        "transportation": "bus",
        "accommodation": "hotel",
        "hotel_name": "Hotel Brahma Horizon Pushkar",
        "hotel_star_rating": 3,
        "transport_details": "RSRTC Volvo from Jaipur + local auto-rickshaw",
        "is_featured": False,
    },
    {
        "title": "Kolkata — The City of Joy Cultural Tour",
        "state": "west_bengal",
        "city_name": "Kolkata",
        "description": "Kolkata captivates with its colonial architecture, literary heritage and warm people. Walk through history at Victoria Memorial, watch the sunset from Howrah Bridge and indulge in street food.",
        "highlights": "Victoria Memorial Museum\nHowrah Bridge & Ganges Ferry\nKalighat Kali Temple\nCollege Street Book Market\nPark Street Food Trail",
        "itinerary": "Arrive Kolkata — check-in ITC Royal Bengal\nVictoria Memorial Museum & Maidan morning walk\nKalighat Kali Temple & Kumartuli potters' quarter\nHowrah Bridge, Ganges ferry ride & flower market\nCollege Street & Park Street food trail — depart",
        "duration_days": 5,
        "max_group_size": 30,
        "price_per_person": 13000,
        "discount_percent": 8,
        "difficulty": "easy",
        "best_season": "winter",
        "transportation": "flight",
        "accommodation": "luxury_hotel",
        "hotel_name": "ITC Royal Bengal",
        "hotel_star_rating": 5,
        "transport_details": "IndiGo Flight + Private AC Car city transfers",
        "is_featured": False,
    },
    # ── TREKKING PACKAGES ──────────────────────────────────────
    {
        "title": "Valley of Flowers — Himalayan Bloom Trek",
        "state": "uttarakhand",
        "city_name": "Govindghat",
        "description": "A UNESCO World Heritage trek through a valley carpeted with hundreds of wild Himalayan flowers. Combined with the sacred Hemkund Sahib Gurudwara at 4,300m for a transcendent experience.",
        "highlights": "Valley of Flowers Exploration\nHemkund Sahib Gurudwara\nGhangaria Base Camp\nNanda Devi Biosphere Reserve\nPushpawati River Trail",
        "itinerary": "Arrive Haridwar — overnight drive to Joshimath\nDrive to Govindghat — trek 13km to Ghangaria base camp\nFull-day exploration of Valley of Flowers meadow\nHemkund Sahib Gurudwara pilgrimage trek (6km up)\nReturn trek to Govindghat — drive to Haridwar, depart",
        "duration_days": 7,
        "max_group_size": 12,
        "price_per_person": 16500,
        "discount_percent": 0,
        "difficulty": "challenging",
        "best_season": "monsoon",
        "transportation": "private_cab",
        "accommodation": "camp",
        "hotel_name": "GMVN Ghangaria Tourist Rest House",
        "hotel_star_rating": 2,
        "transport_details": "Train to Haridwar + Private Hill Taxi to Govindghat",
        "is_featured": True,
    },
    {
        "title": "Kedarkantha — Winter Summit Trek",
        "state": "uttarakhand",
        "city_name": "Sankri",
        "description": "One of India's best winter treks. Kedarkantha summit at 3,810m offers a 360-degree panorama of Himalayan peaks including Swargarohini, Bandarpunch and Black Peak — all blanketed in deep snow.",
        "highlights": "Kedarkantha Summit (3810m)\nJuda Ka Talab Frozen Lake\nSankri Village Trek Base\nDense Oak & Pine Forests\nCampfire under Starlit Sky",
        "itinerary": "Arrive Dehradun — drive 8hrs to Sankri village, check-in\nAcclimatization forest walk through Kedarkantha trail\nTrek Sankri to Juda Ka Talab frozen lake campsite\nTrek to Kedarkantha base camp through snow fields\nPre-dawn summit push — 360-degree panorama — descend\nReturn trek to Sankri — drive Dehradun, depart",
        "duration_days": 6,
        "max_group_size": 10,
        "price_per_person": 13500,
        "discount_percent": 5,
        "difficulty": "challenging",
        "best_season": "winter",
        "transportation": "jeep",
        "accommodation": "camp",
        "hotel_name": "Nature's Abode Eco Camp Sankri",
        "hotel_star_rating": 2,
        "transport_details": "Train to Dehradun + Shared Bolero 4x4 to Sankri",
        "is_featured": False,
    },
    {
        "title": "Triund & Dharamkot Ridge Trek",
        "state": "himachal_pradesh",
        "city_name": "Dharamshala",
        "description": "A perfect trek above Dharamshala with stunning views of the Kangra Valley and Dhauladhar snow range. Start from McLeod Ganj — home of the Dalai Lama — and camp under a brilliant sky.",
        "highlights": "Triund Ridge Summit\nMcLeod Ganj & Tibetan Market\nNamgyal Monastery\nMagic View Campsite\nDhauladhar Snow Wall Views",
        "itinerary": "Arrive Dharamshala — explore McLeod Ganj & Tibetan market\nNamgyal Monastery & Tsuglagkhang Complex visit\nTrek Dharamkot village to Triund Ridge (9km)\nMagic View campsite — stargazing & campfire night\nDescend to McLeod Ganj — depart Dharamshala",
        "duration_days": 5,
        "max_group_size": 15,
        "price_per_person": 12000,
        "discount_percent": 10,
        "difficulty": "moderate",
        "best_season": "summer",
        "transportation": "private_cab",
        "accommodation": "camp",
        "hotel_name": "The Chamba Camp Dharamshala",
        "hotel_star_rating": 4,
        "transport_details": "Volvo Bus from Delhi to Dharamshala overnight",
        "is_featured": False,
    },
    {
        "title": "Dzukou Valley — Trek the Flowers of the East",
        "state": "northeast",
        "city_name": "Kohima",
        "description": "The Valley of Flowers of Northeast India. Dzukou sits at 2,452m on the Nagaland-Manipur border. Its lily-blanketed meadows, pristine streams and solitude make it one of India's most underrated treks.",
        "highlights": "Dzukou Valley Lily Meadows\nKohima War Cemetery\nViswema Tribal Village Culture\nDzukou River Camp\nNagaland Panorama Viewpoint",
        "itinerary": "Arrive Dimapur — drive 3hrs to Kohima, check-in Hotel Japfu\nKohima War Cemetery & State Museum — local Naga cuisine\nDrive Viswema village — begin trek up to Dzukou base\nExplore Dzukou Valley lily meadows — riverside camp\nReturn trek to Viswema — drive Kohima, depart Dimapur",
        "duration_days": 5,
        "max_group_size": 10,
        "price_per_person": 17500,
        "discount_percent": 0,
        "difficulty": "challenging",
        "best_season": "monsoon",
        "transportation": "jeep",
        "accommodation": "camp",
        "hotel_name": "Hotel Japfu Kohima",
        "hotel_star_rating": 3,
        "transport_details": "Flight to Dimapur + Private Jeep to Kohima",
        "is_featured": False,
    },
]

PLACES_DATA = [
    {"name": "Amber Fort", "emoji": "🏰", "specialty": "A majestic 16th-century hilltop fort in Jaipur blending Rajput & Mughal architecture. Famous for Sheesh Mahal (Hall of Mirrors)."},
    {"name": "Mehrangarh Fort", "emoji": "🏰", "specialty": "One of India's largest forts towering 125m above Jodhpur. Its ramparts offer sweeping views of the Blue City."},
    {"name": "Pichola Lake", "emoji": "🌊", "specialty": "An artificial lake in Udaipur with two island palaces — Lake Palace and Jag Mandir. Sunset boat cruises here are iconic."},
    {"name": "Jaisalmer", "emoji": "🏜️", "specialty": "The 'Golden City' carved from honey-yellow sandstone in the heart of the Thar Desert. Its living fort contains havelis and bazaars."},
    {"name": "Rohtang Pass", "emoji": "⛰️", "specialty": "A high mountain pass at 3,978m on the Kullu-Lahaul border. It offers the first snow experience for most visitors."},
    {"name": "Solang Valley", "emoji": "🪂", "specialty": "A side valley near Manali famous for paragliding, zorbing and skiing. In winter it transforms into a snow park."},
    {"name": "Dal Lake", "emoji": "🚣", "specialty": "Srinagar's iconic lake spanning 18 sq km. Life here revolves around shikaras, floating markets, and houseboats."},
    {"name": "Gulmarg", "emoji": "🛷", "specialty": "A high-altitude meadow at 2,650m in Kashmir housing Asia's highest gondola. A premier ski destination."},
    {"name": "Sonamarg", "emoji": "❄️", "specialty": "The 'Meadow of Gold' at 2,800m. Surrounded by glaciers and wildflower meadows, it is the gateway to the Thajiwas glacier."},
    {"name": "Pangong Lake", "emoji": "🌊", "specialty": "A hypnotic high-altitude lake at 4,350m stretching 134km between India and China. Famous for its colour-changing water."},
    {"name": "Khardung La", "emoji": "🛵", "specialty": "One of the world's highest motorable passes at 5,359m. A pilgrimage for bikers connecting Leh to Nubra Valley."},
    {"name": "Nubra Valley", "emoji": "🐪", "specialty": "A tri-armed valley in Ladakh with the world's highest cold desert and Bactrian camel safaris."},
    {"name": "Dudhsagar Falls", "emoji": "💧", "specialty": "A four-tiered waterfall on the Goa-Karnataka border plunging 310m. Resembles a sea of milk."},
    {"name": "Periyar Lake", "emoji": "🛶", "specialty": "An artificial reservoir in the heart of Periyar Tiger Reserve. Boat cruises reveal wild elephants and bison."},
    {"name": "Tsomgo Lake", "emoji": "🌊", "specialty": "A glacial lake at 3,753m near Gangtok, Sikkim. It freezes completely in winter and is sacred to locals."},
    {"name": "Dawki", "emoji": "🛶", "specialty": "A small Meghalaya town where the Umngot River is so crystal clear that boats appear to float in mid-air."},
    {"name": "Kaziranga", "emoji": "🦏", "specialty": "UNESCO World Heritage Site in Assam sheltering two-thirds of the world's one-horned rhinos."},
    {"name": "Ranthambore Fort", "emoji": "🏛️", "specialty": "A UNESCO-protected 10th-century fort inside Ranthambore National Park. Tigers are frequently spotted here."},
    {"name": "Padam Talao", "emoji": "🐊", "specialty": "The largest lake in Ranthambore National Park. A favourite tiger watering hole."},
    {"name": "Valley of Flowers", "emoji": "🌸", "specialty": "A UNESCO World Heritage alpine valley in Uttarakhand carpeted with hundreds of wild Himalayan flowers."},
    {"name": "Hemkund Sahib", "emoji": "🕎", "specialty": "One of the highest Sikh shrines in the world at 4,329m, surrounded by a glacial lake."},
    {"name": "Ghangaria", "emoji": "⛺", "specialty": "The last major settlement before Valley of Flowers, sitting at 3,050m. Basecamp for treks."},
    {"name": "Juda Ka Talab", "emoji": "❅️", "specialty": "A beautiful frozen lake at 2,731m on the Kedarkantha trek, ringed by pine forests."},
    {"name": "Sankri", "emoji": "🏔️", "specialty": "A remote village at 1,920m serving as the base for Kedarkantha. Famous for its apple orchards."},
    {"name": "Triund", "emoji": "🏕️", "specialty": "A ridge at 2,827m above McLeod Ganj offering a 180-degree panoramic view of the Dhauladhar range."},
    {"name": "McLeod Ganj", "emoji": "🛕", "specialty": "A Tibetan enclave above Dharamshala, home to the Dalai Lama. Known for its Buddhist monasteries."},
    {"name": "Namgyal Monastery", "emoji": "☯️", "specialty": "The personal monastery of the Dalai Lama. The largest Tibetan monastery outside of Tibet."},
    {"name": "Mysore Palace", "emoji": "👑", "specialty": "India's second most visited monument. Illuminated by 97,000 light bulbs on Sundays."},
    {"name": "Brindavan Gardens", "emoji": "🌿", "specialty": "Terraced gardens below the KRS Dam. Famous for its musical fountain show at night."},
    {"name": "Chamundi Hills", "emoji": "⛰️", "specialty": "A sacred hill 13km from Mysore topped by the 12th-century Chamundeswari Temple."},
    {"name": "Victoria Memorial", "emoji": "🏰", "specialty": "A magnificent white marble monument in Kolkata built in 1921. Houses 25 galleries."},
    {"name": "Howrah Bridge", "emoji": "🌉", "specialty": "An iconic cantilever bridge over the Hooghly River in Kolkata. Carries 100,000 vehicles daily."},
    {"name": "Pushkar Lake", "emoji": "🪔", "specialty": "One of India's holiest pilgrimage sites with 52 bathing ghats. Hindus believe a dip here washes away sins."},
    {"name": "Dzukou Valley", "emoji": "🌼", "specialty": "A pristine valley at 2,452m carpeted with rare Dzukou lily flowers in July-August."},
    {"name": "Kohima War Cemetery", "emoji": "🕊️", "specialty": "A beautifully maintained WWII cemetery in Nagaland commemorating Allied soldiers."},
    {"name": "Baga Beach", "emoji": "🏖️", "specialty": "One of Goa's most famous and vibrant beaches, known for its water sports and pulsating nightlife."},
    {"name": "Old Goa Churches", "emoji": "⛪", "specialty": "UNESCO World Heritage sites in Old Goa featuring stunning Portuguese colonial architecture."},
    {"name": "Spice Plantation", "emoji": "🌿", "specialty": "Lush tropical farms where you can walk among vanilla, cardamom, and pepper vines."},
    {"name": "Taj Mahal", "emoji": "🕌", "specialty": "An ivory-white marble mausoleum in Agra, one of the Seven Wonders of the World."},
    {"name": "Ganga Aarti", "emoji": "🪔", "specialty": "A deeply spiritual fire offering ritual performed every evening on the banks of the Ganges in Varanasi."},
    {"name": "Kashi Vishwanath Temple", "emoji": "🛕", "specialty": "One of the most famous Hindu temples dedicated to Lord Shiva, located in Varanasi."},
    {"name": "Sarnath", "emoji": "☸️", "specialty": "The deer park where Gautama Buddha first taught the Dharma, located just 10km from Varanasi."},
    {"name": "White Rann", "emoji": "🧂", "specialty": "A massive seasonal salt marsh in the Thar Desert, Gujarat. Stunningly beautiful under a full moon."},
    {"name": "Kala Dungar", "emoji": "⛰️", "specialty": "The highest point in Kutch, offering spectacular panoramic views of the Great Rann of Kutch."},
    {"name": "Virupaksha Temple", "emoji": "🛕", "specialty": "A majestic 7th-century Hindu temple in Hampi, dedicated to Lord Shiva."},
    {"name": "Badami Cave Temples", "emoji": "🪨", "specialty": "A complex of four Hindu and Jain cave temples carved out of red sandstone cliffs."},
    {"name": "Western Group of Temples", "emoji": "🛕", "specialty": "UNESCO World Heritage site in Khajuraho famous for its intricate nagara-style architecture."},
    {"name": "Orchha Fort Complex", "emoji": "🏰", "specialty": "A magnificent 16th-century citadel on the banks of the Betwa River."},
    {"name": "Radhanagar Beach", "emoji": "🏖️", "specialty": "Often voted Asia's best beach, located on Havelock Island with pristine white sand."},
    {"name": "Golden Temple", "emoji": "🕌", "specialty": "The holiest Gurdwara of Sikhism in Amritsar, stunningly clad in gold."},
    {"name": "Wagah Border", "emoji": "🇮🇳", "specialty": "The border crossing between India and Pakistan known for its energetic daily retreat ceremony."},
    {"name": "Jallianwala Bagh", "emoji": "🕊️", "specialty": "A historic garden and memorial in Amritsar commemorating the peaceful gatherers massacred in 1919."},
    {"name": "Key Monastery", "emoji": "🛕", "specialty": "A spectacular 11th-century Tibetan Buddhist monastery perched on a hill in Spiti Valley."},
    {"name": "Chandratal Lake", "emoji": "🌊", "specialty": "The 'Moon Lake' situated at 4,300m in Spiti. Its crescent shape makes it a magical campsite."},
    {"name": "Auroville", "emoji": "🧘", "specialty": "An experimental universal township near Pondicherry dedicated to the ideal of human unity."},
]


class Command(BaseCommand):
    help = 'Seed the database with 25+ India tour packages and destinations'

    def handle(self, *args, **kwargs):
        self.stdout.write(self.style.MIGRATE_HEADING('--- Seeding TourVista India data ---'))

        # 1. Create specific destinations
        for d in DESTINATIONS_DATA:
            obj, created = Destination.objects.get_or_create(
                name=d['name'],
                defaults={
                    'state': d['state'],
                    'description': d['description'],
                    'is_featured': d['is_featured'],
                }
            )
            status = '[Created]' if created else '[Already exists]'
            self.stdout.write(f'  {status}: Destination {obj.name}')

        # 2. Ensure destinations exist for all package states
        all_states = set(p['state'] for p in PACKAGES_DATA)
        for state in all_states:
            Destination.objects.get_or_create(
                state=state,
                defaults={
                    'name': state.replace('_', ' ').title(),
                    'description': f'Explore the beautiful state of {state.replace("_", " ").title()}.',
                }
            )

        self.stdout.write('')

        # 3. Create or update packages
        for p in PACKAGES_DATA:
            image_path = f"packages/{slugify(p['title'])}.jpg"
            exists = TourPackage.objects.filter(title=p['title']).exists()

            if exists:
                TourPackage.objects.filter(title=p['title']).update(
                    main_image=image_path,
                    hotel_name=p.get('hotel_name', ''),
                    hotel_star_rating=p.get('hotel_star_rating'),
                    transport_details=p.get('transport_details', ''),
                    itinerary=p.get('itinerary', ''),
                )
                self.stdout.write(f'  [Updated]: {p["title"]}')
                continue

            pkg = TourPackage.objects.create(
                title=p['title'],
                state=p['state'],
                city_name=p['city_name'],
                description=p['description'],
                highlights=p.get('highlights', ''),
                itinerary=p.get('itinerary', ''),
                duration_days=p['duration_days'],
                max_group_size=p['max_group_size'],
                price_per_person=p['price_per_person'],
                discount_percent=p['discount_percent'],
                difficulty=p['difficulty'],
                best_season=p['best_season'],
                transportation=p['transportation'],
                accommodation=p['accommodation'],
                hotel_name=p.get('hotel_name', ''),
                hotel_star_rating=p.get('hotel_star_rating'),
                transport_details=p.get('transport_details', ''),
                is_featured=p['is_featured'],
                is_active=True,
                main_image=image_path,
            )
            self.stdout.write(f'  [Created]: {pkg.title}')

        self.stdout.write('')

        # 4. Seed Place data for itinerary hover tooltips
        self.stdout.write(self.style.MIGRATE_HEADING('--- Seeding Place tooltip data ---'))
        for pl in PLACES_DATA:
            obj, created = Place.objects.get_or_create(
                name=pl['name'],
                defaults={
                    'specialty': pl['specialty'],
                    'emoji': pl.get('emoji', '📍'),
                }
            )
            if not created:
                obj.specialty = pl['specialty']
                obj.emoji = pl.get('emoji', '📍')
                obj.save()
            status = '[Created]' if created else '[Updated]'
            self.stdout.write(f'  {status}: Place "{obj.name}"')

        self.stdout.write('')
        self.stdout.write(self.style.SUCCESS(
            f'Done! {TourPackage.objects.count()} packages & {Place.objects.count()} places in database.'
        ))
        self.stdout.write(self.style.WARNING(
            'Tip: Add your image files to media/packages/ matching the slugified titles.'
        ))
