# Generated by Django 6.0.4 on 2026-04-24 14:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("rajasthan", "Rajasthan"),
                            ("goa", "Goa"),
                            ("kerala", "Kerala"),
                            ("himachal_pradesh", "Himachal Pradesh"),
                            ("kashmir", "Jammu & Kashmir"),
                            ("uttarakhand", "Uttarakhand"),
                            ("maharashtra", "Maharashtra"),
                            ("tamil_nadu", "Tamil Nadu"),
                            ("karnataka", "Karnataka"),
                            ("west_bengal", "West Bengal"),
                            ("gujarat", "Gujarat"),
                            ("andaman", "Andaman & Nicobar"),
                            ("uttar_pradesh", "Uttar Pradesh"),
                            ("northeast", "Northeast India"),
                            ("punjab", "Punjab"),
                            ("madhya_pradesh", "Madhya Pradesh"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="destinations/"),
                ),
                ("is_featured", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="TourPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("rajasthan", "Rajasthan"),
                            ("goa", "Goa"),
                            ("kerala", "Kerala"),
                            ("himachal_pradesh", "Himachal Pradesh"),
                            ("kashmir", "Jammu & Kashmir"),
                            ("uttarakhand", "Uttarakhand"),
                            ("maharashtra", "Maharashtra"),
                            ("tamil_nadu", "Tamil Nadu"),
                            ("karnataka", "Karnataka"),
                            ("west_bengal", "West Bengal"),
                            ("gujarat", "Gujarat"),
                            ("andaman", "Andaman & Nicobar"),
                            ("uttar_pradesh", "Uttar Pradesh"),
                            ("northeast", "Northeast India"),
                            ("punjab", "Punjab"),
                            ("madhya_pradesh", "Madhya Pradesh"),
                        ],
                        default="rajasthan",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "highlights",
                    models.TextField(blank=True, help_text="One highlight per line"),
                ),
                (
                    "itinerary",
                    models.TextField(blank=True, help_text="Day-wise itinerary"),
                ),
                ("inclusions", models.TextField(blank=True)),
                ("exclusions", models.TextField(blank=True)),
                ("duration_days", models.PositiveIntegerField(default=3)),
                ("max_group_size", models.PositiveIntegerField(default=20)),
                (
                    "price_per_person",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("discount_percent", models.PositiveIntegerField(default=0)),
                (
                    "difficulty",
                    models.CharField(
                        choices=[
                            ("easy", "Easy"),
                            ("moderate", "Moderate"),
                            ("challenging", "Challenging"),
                            ("extreme", "Extreme"),
                        ],
                        default="easy",
                        max_length=20,
                    ),
                ),
                (
                    "best_season",
                    models.CharField(
                        choices=[
                            ("all", "All Year"),
                            ("summer", "Summer (Mar–Jun)"),
                            ("monsoon", "Monsoon (Jul–Sep)"),
                            ("winter", "Winter (Oct–Feb)"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                (
                    "transportation",
                    models.CharField(
                        choices=[
                            ("flight", "Flight"),
                            ("train", "Train"),
                            ("bus", "Bus"),
                            ("private_cab", "Private Cab"),
                            ("houseboat", "Houseboat"),
                            ("jeep", "4WD Jeep"),
                        ],
                        default="flight",
                        max_length=30,
                    ),
                ),
                (
                    "accommodation",
                    models.CharField(
                        choices=[
                            ("luxury_hotel", "Luxury Hotel (5★)"),
                            ("hotel", "Hotel (3–4★)"),
                            ("resort", "Resort"),
                            ("homestay", "Homestay"),
                            ("hostel", "Hostel"),
                            ("camp", "Camping"),
                            ("houseboat", "Houseboat"),
                        ],
                        default="hotel",
                        max_length=30,
                    ),
                ),
                (
                    "main_image",
                    models.ImageField(blank=True, null=True, upload_to="packages/"),
                ),
                (
                    "image_2",
                    models.ImageField(blank=True, null=True, upload_to="packages/"),
                ),
                (
                    "image_3",
                    models.ImageField(blank=True, null=True, upload_to="packages/"),
                ),
                (
                    "image_4",
                    models.ImageField(blank=True, null=True, upload_to="packages/"),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "city_name",
                    models.CharField(
                        blank=True,
                        help_text="City name for weather API (e.g. Jaipur)",
                        max_length=100,
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.destination",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_featured", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=100)),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="core.tourpackage",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("package", "user")},
            },
        ),
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.tourpackage",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wishlist",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "package")},
            },
        ),
    ]
