# Generated by Django 6.0.3 on 2026-04-25 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, unique=True)),
                (
                    "specialty",
                    models.TextField(
                        help_text="Short description of what makes this place special"
                    ),
                ),
                ("emoji", models.CharField(blank=True, default="📍", max_length=10)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="tourpackage",
            name="hotel_name",
            field=models.CharField(
                blank=True,
                help_text="Specific hotel name, e.g. Taj Lake Palace",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="tourpackage",
            name="hotel_star_rating",
            field=models.PositiveIntegerField(
                blank=True,
                choices=[
                    (1, "1 Star"),
                    (2, "2 Star"),
                    (3, "3 Star"),
                    (4, "4 Star"),
                    (5, "5 Star"),
                ],
                help_text="Hotel star rating 1–5",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tourpackage",
            name="transport_details",
            field=models.CharField(
                blank=True,
                help_text="e.g. Indigo Flight + Private Innova Crysta",
                max_length=255,
            ),
        ),
    ]
