# Generated by Django 6.0.3 on 2026-04-25 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_place_tourpackage_hotel_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="place",
            name="image_url",
            field=models.URLField(
                blank=True,
                help_text="Direct URL to a high-quality image (e.g., Unsplash)",
                max_length=500,
                null=True,
            ),
        ),
    ]
