# Generated by Django 6.0.3 on 2026-04-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_place_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="place",
            name="image_url",
        ),
        migrations.AddField(
            model_name="place",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload a cover photo for the tooltip",
                null=True,
                upload_to="places/",
            ),
        ),
    ]
