# Generated by Django 6.0.3 on 2026-04-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_place_image_url_place_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeasonInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "season_type",
                    models.CharField(
                        choices=[
                            ("winter", "Winter"),
                            ("summer", "Summer"),
                            ("monsoon", "Monsoon"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="e.g. The Himalayan Escape", max_length=150
                    ),
                ),
                ("description", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        help_text="Featured image for this season", upload_to="seasons/"
                    ),
                ),
                (
                    "avg_temp",
                    models.CharField(help_text="e.g. 12°C - 25°C", max_length=50),
                ),
                (
                    "festivals",
                    models.TextField(help_text="Major festivals separated by commas"),
                ),
                (
                    "north_india",
                    models.CharField(
                        help_text="Best places in North India", max_length=255
                    ),
                ),
                (
                    "south_india",
                    models.CharField(
                        help_text="Best places in South India", max_length=255
                    ),
                ),
                (
                    "west_india",
                    models.CharField(
                        help_text="Best places in West India", max_length=255
                    ),
                ),
                (
                    "east_india",
                    models.CharField(
                        help_text="Best places in East India", max_length=255
                    ),
                ),
            ],
            options={
                "verbose_name": "Season Information",
                "verbose_name_plural": "Season Information",
            },
        ),
    ]
