# Generated by Django 6.0.4 on 2026-04-27 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_seasoninfo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SeasonInfo",
        ),
    ]
