# Generated by Django 6.0.3 on 2026-04-27 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_seasoninfo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SeasonInfo",
        ),
    ]
