# Generated by Django 6.0.3 on 2026-04-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_delete_seasoninfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tourpackage",
            name="best_season",
            field=models.CharField(
                choices=[
                    ("all", "All Year"),
                    ("summer", "Summer (Mar–Jun)"),
                    ("monsoon", "Monsoon (Jul–Sep)"),
                    ("autumn", "Autumn (Oct–Nov)"),
                    ("winter", "Winter (Dec–Feb)"),
                ],
                default="all",
                max_length=20,
            ),
        ),
    ]
