# Generated by Django 6.0.4 on 2026-04-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_alter_tourpackage_best_season"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination",
            name="latitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="longitude",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=9, null=True
            ),
        ),
        migrations.AlterField(
            model_name="destination",
            name="state",
            field=models.CharField(
                choices=[
                    ("rajasthan", "Rajasthan"),
                    ("goa", "Goa"),
                    ("kerala", "Kerala"),
                    ("himachal_pradesh", "Himachal Pradesh"),
                    ("kashmir", "Jammu & Kashmir"),
                    ("uttarakhand", "Uttarakhand"),
                    ("maharashtra", "Maharashtra"),
                    ("tamil_nadu", "Tamil Nadu"),
                    ("karnataka", "Karnataka"),
                    ("west_bengal", "West Bengal"),
                    ("gujarat", "Gujarat"),
                    ("andaman", "Andaman & Nicobar"),
                    ("uttar_pradesh", "Uttar Pradesh"),
                    ("northeast", "Northeast India"),
                    ("punjab", "Punjab"),
                    ("madhya_pradesh", "Madhya Pradesh"),
                    ("tripura", "Tripura"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="tourpackage",
            name="state",
            field=models.CharField(
                choices=[
                    ("rajasthan", "Rajasthan"),
                    ("goa", "Goa"),
                    ("kerala", "Kerala"),
                    ("himachal_pradesh", "Himachal Pradesh"),
                    ("kashmir", "Jammu & Kashmir"),
                    ("uttarakhand", "Uttarakhand"),
                    ("maharashtra", "Maharashtra"),
                    ("tamil_nadu", "Tamil Nadu"),
                    ("karnataka", "Karnataka"),
                    ("west_bengal", "West Bengal"),
                    ("gujarat", "Gujarat"),
                    ("andaman", "Andaman & Nicobar"),
                    ("uttar_pradesh", "Uttar Pradesh"),
                    ("northeast", "Northeast India"),
                    ("punjab", "Punjab"),
                    ("madhya_pradesh", "Madhya Pradesh"),
                    ("tripura", "Tripura"),
                ],
                default="rajasthan",
                max_length=50,
            ),
        ),
    ]
