# Generated by Django 6.0.4 on 2026-04-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_destination_latitude_destination_longitude_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="destination",
            name="category",
            field=models.CharField(
                choices=[
                    ("Heritage", "Heritage"),
                    ("Beach", "Beach"),
                    ("Hills", "Hills"),
                    ("Adventure", "Adventure"),
                    ("Spiritual", "Spiritual"),
                    ("Nature", "Nature"),
                ],
                default="Heritage",
                max_length=50,
            ),
        ),
    ]
