# Generated by Django 6.0.4 on 2026-05-03 07:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_alter_destination_state_alter_tourpackage_state"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="destination",
            index=models.Index(fields=["state"], name="core_destin_state_890ebf_idx"),
        ),
        migrations.AddIndex(
            model_name="destination",
            index=models.Index(
                fields=["is_featured"], name="core_destin_is_feat_292a85_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["rating"], name="core_review_rating_41e437_idx"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["created_at"], name="core_review_created_25a366_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tourpackage",
            index=models.Index(
                fields=["is_active"], name="core_tourpa_is_acti_974e4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tourpackage",
            index=models.Index(fields=["state"], name="core_tourpa_state_2ce407_idx"),
        ),
        migrations.AddIndex(
            model_name="tourpackage",
            index=models.Index(
                fields=["price_per_person"], name="core_tourpa_price_p_f845f9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tourpackage",
            index=models.Index(
                fields=["is_featured", "created_at"],
                name="core_tourpa_is_feat_fc3bfd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="tourpackage",
            index=models.Index(
                fields=["is_active", "state"], name="core_tourpa_is_acti_490435_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tourpackage",
            index=models.Index(
                fields=["difficulty"], name="core_tourpa_difficu_24e22f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tourpackage",
            index=models.Index(
                fields=["best_season"], name="core_tourpa_best_se_08db65_idx"
            ),
        ),
    ]
