# Generated by Django 6.0.4 on 2026-05-03 07:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
        ("core", "0013_destination_core_destin_state_890ebf_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["status"], name="bookings_bo_status_233e96_idx"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["created_at"], name="bookings_bo_created_1720a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["travel_date"], name="bookings_bo_travel__83d735_idx"
            ),
        ),
    ]
