# Generated by Django 6.0.4 on 2026-05-03 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0003_payment_razorpay_order_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="razorpay_order_id",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="razorpay_payment_id",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="razorpay_signature",
        ),
    ]
